### ISSUE TITLE
Naming convention in Listing Struct

### ISSUE THREAD

**Issue by kangarang** [AdChain/AdChainRegistry#15]
The `currentDeposit` member of the Listing struct in `Registry.sol` could be named differently to clarify it's purpose. During challenges, the `currentDeposit` is decreased by the challenger.

**Comment by kangarang** [comment]
4. `unlockedDeposit`
5. `unlockedStake`
6. `unlockedTokens`
7. `securityDeposit`
8. `unlockedSecurityDeposit`

**Comment by skmgoldin** [comment]
Lets go for unlockedDeposit. I will accept a PR to this effect.
