### ISSUE TITLE
Suspect there is a race condition in registry.js

### ISSUE THREAD

**Issue by skmgoldin** [AdChain/AdChainRegistry#26]
I got a `Key not found in database` which is a strong indicator. I've also had my console hang on test "completion".

**Comment by kangarang** [comment]
Did this start happening recently?

**Comment by skmgoldin** [comment]
I have not been able to reproduce this even after instrumenting the tests. May have been on a dirty branch while developing. Going to close this.

**Comment by kangarang** [comment]
![screenshot from 2017-10-01 14-07-24](https://user-images.githubusercontent.com/18040654/31057517-ecbf8bd6-a6b1-11e7-9fb8-490d91755165.png)

**Comment by kangarang** [comment]
https://github.com/ethereumjs/testrpc/issues/359
