### ISSUE TITLE
Typo error

### ISSUE THREAD

**Issue by eccheung4** [AdChain/AdChainRegistry#30]
https://github.com/AdChain/AdChainRegistry/blob/master/contracts/Registry.sol#L242
"==" instead of "="

**Comment by skmgoldin** [comment]
Damn, how did our tests not get this. Lets do a decomposition of that before fixing @kangarang. Thanks Ed.

**Comment by skmgoldin** [comment]
Good thing _somebody_ is reading this code. 🙄

**Comment by skmgoldin** [comment]
I'm actually gonna do a hotfix right now Ed.

**Comment by kangarang** [comment]
Great catch @eccheung4 . @skmgoldin 

We don't have any test coverage on `claimReward` and it's never invoked within `Registry.sol`, so at least we have that going for us.

**Comment by skmgoldin** [comment]
Hotfix committed, new contracts deployed to Rinkeby and pushed to S3.

> We don't have any test coverage on claimReward
We gotta fill in those stubs.

**Comment by eccheung4** [comment]
Same typo error

https://github.com/AdChain/AdChainRegistry/blob/master/contracts/Parameterizer.sol#L194

**Comment by kangarang** [comment]
Thanks @eccheung4 . 

@skmgoldin is traveling at the moment and will redeploy the contracts probably in the next day or so.

**Comment by eccheung4** [comment]
cool, no hurry to redeploy
